'use server';
/**
 * @fileOverview An AI agent for generating images from text descriptions.
 *
 * - aiImageCreation - A function that handles the image generation process.
 * - AiImageCreationInput - The input type for the aiImageCreation function.
 * - AiImageCreationOutput - The return type for the aiImageCreation function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const AiImageCreationInputSchema = z.object({
  prompt: z.string().describe('A text description of the image to be generated.'),
});
export type AiImageCreationInput = z.infer<typeof AiImageCreationInputSchema>;

const AiImageCreationOutputSchema = z.object({
  media: z.string().describe('The generated image as a data URI.'),
});
export type AiImageCreationOutput = z.infer<typeof AiImageCreationOutputSchema>;

export async function aiImageCreation(
  input: AiImageCreationInput
): Promise<AiImageCreationOutput> {
  return aiImageCreationFlow(input);
}

const aiImageCreationFlow = ai.defineFlow(
  {
    name: 'aiImageCreationFlow',
    inputSchema: AiImageCreationInputSchema,
    outputSchema: AiImageCreationOutputSchema,
  },
  async (input) => {
    const { media } = await ai.generate({
      model: 'googleai/imagen-4.0-fast-generate-001',
      prompt: input.prompt,
    });

    if (!media) {
      throw new Error('No media generated by the image model.');
    }

    return { media: media.url };
  }
);
